### ISSUE TITLE
Create a python installer package

### ISSUE THREAD

**Issue by anoopkunchukuttan** [anoopkunchukuttan/indic_nlp_library#1]

**Comment by arnavsharma93** [comment]
I can do this for you if you want.

**Comment by anoopkunchukuttan** [comment]
That would be great. I have been procrastinating over learning how to
create an installer package for long. What installer do u you have in mind-
easyinstall?

**Comment by arcturusannamalai** [comment]
@anoopkunchukuttan you can take a look at https://github.com/Ezhil-Language-Foundation/open-tamil/blob/master/setup.py and reproduce it for your purposes. This works well on all 3 (2x NIX + WIN) platforms.

**Comment by anoopkunchukuttan** [comment]
@arcturusannamalai , Thanks for the info, I will try this.

**Comment by vamshi2592** [comment]
Is there an installable python package available for indicNLP from pip?

If no, it would be helpful if anyone has successfully created a python package and happy to share.

**Comment by anoopkunchukuttan** [comment]
Published on pip recently, check readme
