### ISSUE TITLE
morph_analyze_document should form a list of lists

### ISSUE THREAD

**Issue by martiansideofthemoon** [anoopkunchukuttan/indic_nlp_library#12]
My reference is to https://github.com/anoopkunchukuttan/indic_nlp_library/blob/925e3d4414b824954711edd81597832d2419d847/src/indicnlp/morph/unsupervised_morph.py#L93

Instead of `extend()`, could you use `append()` to make a more easy to use list of lists?

**Comment by anoopkunchukuttan** [comment]
I agree. Thanks for the suggestion. I will make the changes.

**Comment by anoopkunchukuttan** [comment]
Changes made

**Comment by martiansideofthemoon** [comment]
Thank you @anoopkunchukuttan! Great library :smile:
