### ISSUE TITLE
Morphogical analyser

### ISSUE THREAD

**Issue by ashnamp** [anoopkunchukuttan/indic_nlp_library#13]
self._script_range_pat=ur'^[{}-{}]+$'.format(unichr(langinfo.SCRIPT_RANGES[lang][0]),unichr(langinfo.SCRIPT_RANGES[lang][1]))
                                        ^
SyntaxError: invalid syntax

**Comment by anoopkunchukuttan** [comment]
Which language are you using the unsupervised morph for?

**Comment by ashnamp** [comment]
python3.5

**Comment by anoopkunchukuttan** [comment]
I haven't tested on python 3.5, but my question was regarding which language's morph analyzer (Hindi, Malayalam, etc.) were you trying to use?

**Comment by ashnamp** [comment]
Malayalam

**Comment by anoopkunchukuttan** [comment]
I checked Python2.7, the code works fine. On Python 3.5 I was able to reproduce the same error you mention. I will have to check what need to be done to support Python 3.5. As of now, the library has been test for Python 2 versions only.

**Comment by anoopkunchukuttan** [comment]
I happened to fix another bug while debugging this one. So pull the latest checkin for the fix

**Comment by arcturusannamalai** [comment]
In Python3 generators need to be forced to list via 'list()' call before you may index it. This may just work.

**Comment by arcturusannamalai** [comment]
@erzaliator - can you use a library like 'six' to make it straddle the 2-3 divide ? That way you could even recommit code back to this project.
