### ISSUE TITLE
indic_tokenize

### ISSUE THREAD

**Issue by hlsrekha** [anoopkunchukuttan/indic_nlp_library#14]
hai, I'm trying to use indic_tokenize.  I got he following message. Im using Python 3.6

  File "C:/Users/CS-14/Anaconda3/lib/site-packages/indicnlp/tokenize/indic_tokenize.py", line 27
    triv_tokenizer_indic_pat=re.compile(ur'(['+string.punctuation+ur'\u0964\u0965'+ur'])')
                                             ^
SyntaxError: invalid syntax.
Can you help to get rid of this error.
Thanks

**Comment by anoopkunchukuttan** [comment]
The library currently works with Python 2.X only. Python 3.X is not supported yet.
