### ISSUE TITLE
unable to use indic_nlp_library

### ISSUE THREAD

**Issue by riktimmondal** [anoopkunchukuttan/indic_nlp_library#18]
Traceback (most recent call last):
  File "indic_nlp_library-master/src/indicnlp/tokenize/indic_tokenize.py", line 27, in <module>
    from indicnlp.common import IndicNlpException
ModuleNotFoundError: No module named 'indicnlp'

Even after exporting the path I am getting this error.

**Comment by arcturusannamalai** [comment]
You have to install the module @riktimmondal - try 'cd indic_nlp_library-master && python setup.py sdist build_and_install'

**Comment by riktimmondal** [comment]
python: can't open file 'setup.py': [Errno 2] No such file or directory
There is no as such any setup.py file in the repository

**Comment by arcturusannamalai** [comment]
You can just set a environment variable 
$ export PYTHONPATH 'full/path/to/here/indic_nlp_library/src/' 
$ python -c 'import indic_nlp_library'

should work if you have BASH and Linux.

**Comment by riktimmondal** [comment]
Thanks issue has been resolved.
