### ISSUE TITLE
Computing similarity between languages

### ISSUE THREAD

**Issue by PVinay737** [anoopkunchukuttan/indic_nlp_library#25]
Is there a documentation support to find similarity between two languages ? If so,can you include an example here

**Comment by anoopkunchukuttan** [comment]
I just added support for computing similarity between two string across languages. Please pull latest version of the library. An example of computing the similarity between two strings is shown in the Ipython Notebook [now](https://nbviewer.jupyter.org/url/anoopkunchukuttan.github.io/indic_nlp_library/doc/indic_nlp_examples.ipynb#Lexical-Similarity). To compute the similarity between two languages, you would need a parallel corpus. Then you can compute the lexical similarity between every sentence pair and average them to compute the lexical similarity.

**Comment by PVinay737** [comment]
Thanks for adding it @anoopkunchukuttan 

Exactly the one I was looking for !

**Comment by chiragsanghvi10** [comment]
Hi @anoopkunchukuttan,
Thank you for this repository, 

Is it possible to find out lexical similarity between Hindi and English?

**Comment by anoopkunchukuttan** [comment]
It is not possible with this library - the scripts, word order are different. Quite a challenge given how these two languages have diverged over time.
