### ISSUE TITLE
Unable to do Machine Translation

### ISSUE THREAD

**Issue by aastha19** [anoopkunchukuttan/indic_nlp_library#26]
Hi 
Running the following snippet of code results in JSONDecodeError  :

Code Snippet
![image](https://user-images.githubusercontent.com/14852345/68271125-9f362e80-0085-11ea-93c3-5cf868f17baa.png)

Error:
![image](https://user-images.githubusercontent.com/14852345/68271183-c7259200-0085-11ea-8dbe-b3110cbd3b51.png)

**Comment by anoopkunchukuttan** [comment]
I will check and get back

**Comment by aastha19** [comment]
ok thanks

**Comment by aastha19** [comment]
@anoopkunchukuttan any update?

**Comment by harshalwavre7** [comment]
The API of Brahmi-Net does not have translate end point and hence it is throwing error
![Brahmi-Net](https://user-images.githubusercontent.com/26541367/71890986-8cb2a100-316b-11ea-8edb-0343caa4d7e8.PNG)
Hence it is giving error

**Comment by anoopkunchukuttan** [comment]
Not supporting translation any longer from IndicNLP library. However, the BrahmiNet API may be available.
