### ISSUE TITLE
Detect the language of transliterated text

### ISSUE THREAD

**Issue by bnriiitb** [anoopkunchukuttan/indic_nlp_library#33]
Is there any functionality to detect the language of a transliterated text?

**Comment by anoopkunchukuttan** [comment]
No, there is no functionality today. Do you have sufficient transliterated text in the language. It will be easy to train a language identificerif you have such data.

**Comment by bnriiitb** [comment]
Thank you @anoopkunchukuttan  for the response.
I have a lot of transliterated text but the concern is it's not tagged  and also some times a single text has transliterated words of multiple languages
