### ISSUE TITLE
vectors for SOS and EOS

### ISSUE THREAD

**Issue by sumyuck** [anoopkunchukuttan/indic_nlp_library#34]
I wanted to know if there is any vector representation for SOS and EOS in the Hindi embeddings.

**Comment by anoopkunchukuttan** [comment]
Which Hindi embeddings do you mean?

**Comment by sumyuck** [comment]
indicnlp.v1.hi.vec

**Comment by anoopkunchukuttan** [comment]
No, we do not have a vector representation for SOS and EOS. I don't think they will be particularly informative when it comes to word embeddings since they will occur in all sorts of contexts.
