### ISSUE TITLE
Transliteration not working 

### ISSUE THREAD

**Issue by RaviTeja51** [anoopkunchukuttan/indic_nlp_library#35]
Python version: 3.8.9

`pip install indic-nlp-library`
`git clone https://github.com/anoopkunchukuttan/indic_nlp_resources.git`
`import sys
from indicnlp import common
INDIC_NLP_RESOURCES=r"/home/user/indic_nlp_resources"

common.set_resources_path(INDIC_NLP_RESOURCES)
from indicnlp.transliterate.unicode_transliterate import ItransTransliterator
input_text='അടിക്ക് മോനെ'
print(ItransTransliterator.to_itrans(input_text, 'mal'))`

> Output

`അടിക്ക് മോനെ`

I tried both in my local PC and in colab, but the api  is not transliterating 

[colab](https://colab.research.google.com/drive/1Bd88rl9R6T4GtnNJ9z50UQ821pObi7ly?usp=sharing)

**Comment by anoopkunchukuttan** [comment]
Use 'ml' as the language code. IndicNLP library uses 2-letter ISO language codes

**Comment by RaviTeja51** [comment]
I have tried using 'ml' as language code. 
`from indicnlp.transliterate.unicode_transliterate import ItransTransliterator `
`input_text='അടിക്ക് മോനെ'`
`print(ItransTransliterator.to_itrans(input_text, 'ml'))`

output: 
`അി ോെ
`
Sorry i am bit novice please help me

**Comment by anoopkunchukuttan** [comment]
I checked you colab notebook. 

You need to add these: 

from indicnlp import loader

and call 

loader.load() 

before invoking any API operations

**Comment by RaviTeja51** [comment]
Thanks for your help it is working now . I am closing this issue

**Comment by ayanatherate** [comment]
Hi! The above 

> I checked you colab notebook.
> 
> You need to add these:
> 
> from indicnlp import loader
> 
> and call
> 
> loader.load()
> 
> before invoking any API operations

Hi, this seems to resolve the problem with ml and even with hindi. But, it's not working with bengali. Any help from your side would be appreciated!

**Comment by ankitmeher** [comment]
Can anyone provide the working code of transliteration please
