### ISSUE TITLE
Is translate function available?

### ISSUE THREAD

**Issue by udaykumar1998** [anoopkunchukuttan/indic_nlp_library#48]
I have tried to find the translate function but to no avail. The zip file or the github repo dont show any translate option. It is stated in the document that translate is one of the options available. Please help anyone

**Comment by anoopkunchukuttan** [comment]
The translate function is not available as part of this library. But, we recently released translation models for Indian languages - called IndicTrans. You can use those: https://github.com/AI4Bharat/indicTrans
