### ISSUE TITLE
Inappropriate Hindi English Transliteration

### ISSUE THREAD

**Issue by Sonali210** [anoopkunchukuttan/indic_nlp_library#52]
Code:
```
from indicnlp.transliterate.unicode_transliterate import ItransTransliterator
from indicnlp import loader
from indicnlp import common
common.set_resources_path(INDIC_RESOURCES_PATH)
loader.load()
ItransTransliterator.to_itrans('मैं आज आपकी किस प्रकार सहायता कर सकता हूँ?', 'hi')
```
Output:
```
mai.m aaja aapakii kisa prakaara sahaayataa kara sakataa huuँ?
```
[Output using google translator](https://www.google.com/search?q=online+google+translator&rlz=1C1ONGR_enIN977IN977&oq=online+googl&aqs=chrome.1.69i57j69i59j0i512l3j0i433i512j0i512l4.3808j0j7&sourceid=chrome&ie=UTF-8):

Main aaj aapakee kis prakaar sahaayata kar sakata hoon?

There is unnecessary use of '.' and 'uँ' in romanization. What can be the best solution that gives appropriate and presentable transliterated output.

**Comment by anoopkunchukuttan** [comment]
What IndicNLP library supports is a deterministic transliteration to s defined scheme (itrans) in this case. In case you want to use natural transliteration - please use the IndicXlit model we developed at AI4Bharat. 

https://github.com/AI4Bharat/IndicXlit
