### ISSUE TITLE
Text Normalisation using Indic NLP library not working

### ISSUE THREAD

**Issue by lusifer021** [anoopkunchukuttan/indic_nlp_library#54]
from indicnlp.normalize.indic_normalize import IndicNormalizerFactory

input_text="சில உன்னத வேலைகளைச் செய்ய மனிதன் இந்த உலகில் பிறக்கிறான். அவர் வாழ்க்கையில் ஒரு உன்னத இலக்கு இருக்க வேண்டும். அவர் எட்டாம் வகுப்பு மாணவனாக இருக்கும்போது இந்த இலக்கை நிர்ணயிக்க வேண்டும். அதற்கு அவர் உண்மையான முயற்சிகளை மேற்கொள்ள வேண்டும். இது அவருக்கு வெற்றியைத் தரும், மேலும் அவர் தனது இலக்கை அடைய முடியும்"
remove_nuktas=False
factory=IndicNormalizerFactory()
normalizer=factory.get_normalizer("ta",remove_nuktas=False)
output_text=normalizer.normalize(input_text)

print(input_text)
print(output_text)

The text normalisation is not working with this code, it gives back the same string regardless of remove_nuktas is true or false, can you tell what am I doing wrong?

**Comment by oligoglot** [comment]
I think remove_nuktas will not have any impact on Tamil text as we don't
have nuktas. Unless we expand the definition to include other diacritics.

Sundar

**Comment by anoopkunchukuttan** [comment]
Sundar is right. Thanks @oligoglot . Closing.
