### ISSUE TITLE
BrahmiNet is down

### ISSUE THREAD

**Issue by ma08** [anoopkunchukuttan/indic_nlp_library#57]
I understand this is not a library issue, but the BrahmiNet API referenced in the Transliteration example in [this tutorial notebok](https://nbviewer.org/url/anoopkunchukuttan.github.io/inic_nlp_library/doc/indic_nlp_examples.ipynb) isn't working (404 error)

The website links and the web interface are also giving 404.

Thanks,
Sourya

**Comment by anoopkunchukuttan** [comment]
Hi Sourya, 
We have better transliteration systems today. I would recommend using IndicXlit for transliteration we released at AI4Bharat: 

https://github.com/AI4Bharat/IndicXlit

**Comment by ma08** [comment]
I see.

Will check it out, thanks for the response!
