### ISSUE TITLE
Broken "Getting Started" links

### ISSUE THREAD

**Issue by Rhitabrat** [anoopkunchukuttan/indic_nlp_library#62]
Check [this IPython Notebook](http://nbviewer.ipython.org/url/anoopkunchukuttan.github.io/indic_nlp_library/doc/indic_nlp_examples.ipynb) for examples to use the Python API.

You can find the Python 2.x Notebook [here](http://nbviewer.ipython.org/url/anoopkunchukuttan.github.io/indic_nlp_library/doc/indic_nlp_examples_2_7.ipynb)

--------------------------------------------------

Both links are no longer working.

**Comment by snehilk1312** [comment]
The first link is working fine as on 29/04/23. 

Although , Python 2.x Notebook is giving 404 error

**Comment by anoopkunchukuttan** [comment]
I think for a few days, the domain had changed from nbviewer to something else. Seems like it has been restored. Closing.
