### ISSUE TITLE
Introduction to the CLTK

### ISSUE THREAD

**Issue by kylepjohnson** [anoopkunchukuttan/indic_nlp_library#8]
Hi @anoopkunchukuttan,

I just learned of your fantastic library from @Akirato, a contributor to my project, the [CLTK](https://github.com/cltk/cltk). We share many of the same goals, including offering good NLP functionality for students of Indian languages.

I'm writing to introduce myself and let you know that we may have some questions for you, if we should port parts of your code to the CLTK. Of course, all of your work will be fully credited by us.

Thank you for your great work!

Kyle

**Comment by anoopkunchukuttan** [comment]
Hi Kyle, 

Sorry for the late reply.

Good to hear from you. I found the CLTK project very interesting and would be happy if the Indic NLP library is useful in extending it to  classical Indian languages. I see that there is corpus support for Sanskrit and Pali. Appreciate you making clean and parallel corpus available for these  languages. Thanks for that!

Indic NLP Library  is under active development, and I do keep adding features. Please feel free to contact me in case you have any questions about the library. 

Regards,
Anoop.

**Comment by kylepjohnson** [comment]
Thank you @anoopkunchukuttan for sharing your code with us!

If you ever want to take a leading role in the CLTK's Indian languages, let me know and we will make room for you.

**Comment by anoopkunchukuttan** [comment]
Sure, I will. Please note that you will not be able to use this library for commercial purposes.

**Comment by kylepjohnson** [comment]
>  Please note that you will not be able to use this library for commercial purposes.
Of course. The CLTK is MIT license except where noted in individual modules. I add 'GPLv3' and your name to every module based on your code. Is this OK with you?

**Comment by anoopkunchukuttan** [comment]
Sure, that is fine.
